#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKTTH
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SQL_DACS2")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Lop(tbl_Lop instance);
    partial void Updatetbl_Lop(tbl_Lop instance);
    partial void Deletetbl_Lop(tbl_Lop instance);
    partial void Inserttbl_SinhVien(tbl_SinhVien instance);
    partial void Updatetbl_SinhVien(tbl_SinhVien instance);
    partial void Deletetbl_SinhVien(tbl_SinhVien instance);
    partial void Inserttbl_LichThi(tbl_LichThi instance);
    partial void Updatetbl_LichThi(tbl_LichThi instance);
    partial void Deletetbl_LichThi(tbl_LichThi instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SQL_DACS2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Lop> tbl_Lops
		{
			get
			{
				return this.GetTable<tbl_Lop>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SinhVien> tbl_SinhViens
		{
			get
			{
				return this.GetTable<tbl_SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LichThi> tbl_LichThis
		{
			get
			{
				return this.GetTable<tbl_LichThi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Lop")]
	public partial class tbl_Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_lop_th;
		
		private string _ten_lop_th;
		
		private EntitySet<tbl_SinhVien> _tbl_SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_lop_thChanging(string value);
    partial void Onid_lop_thChanged();
    partial void Onten_lop_thChanging(string value);
    partial void Onten_lop_thChanged();
    #endregion
		
		public tbl_Lop()
		{
			this._tbl_SinhViens = new EntitySet<tbl_SinhVien>(new Action<tbl_SinhVien>(this.attach_tbl_SinhViens), new Action<tbl_SinhVien>(this.detach_tbl_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lop_th", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_lop_th
		{
			get
			{
				return this._id_lop_th;
			}
			set
			{
				if ((this._id_lop_th != value))
				{
					this.Onid_lop_thChanging(value);
					this.SendPropertyChanging();
					this._id_lop_th = value;
					this.SendPropertyChanged("id_lop_th");
					this.Onid_lop_thChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_lop_th", DbType="NVarChar(100)")]
		public string ten_lop_th
		{
			get
			{
				return this._ten_lop_th;
			}
			set
			{
				if ((this._ten_lop_th != value))
				{
					this.Onten_lop_thChanging(value);
					this.SendPropertyChanging();
					this._ten_lop_th = value;
					this.SendPropertyChanged("ten_lop_th");
					this.Onten_lop_thChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Lop_tbl_SinhVien", Storage="_tbl_SinhViens", ThisKey="id_lop_th", OtherKey="id_lop_th")]
		public EntitySet<tbl_SinhVien> tbl_SinhViens
		{
			get
			{
				return this._tbl_SinhViens;
			}
			set
			{
				this._tbl_SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_SinhViens(tbl_SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Lop = this;
		}
		
		private void detach_tbl_SinhViens(tbl_SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SinhVien")]
	public partial class tbl_SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sv;
		
		private string _ten_sv;
		
		private string _lop_sv;
		
		private string _ma_sv;
		
		private string _ngay_sinh_sv;
		
		private string _dia_chi_sv;
		
		private int _sdt_sv;
		
		private string _id_lop_th;
		
		private EntitySet<tbl_LichThi> _tbl_LichThis;
		
		private EntityRef<tbl_Lop> _tbl_Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_svChanging(int value);
    partial void Onid_svChanged();
    partial void Onten_svChanging(string value);
    partial void Onten_svChanged();
    partial void Onlop_svChanging(string value);
    partial void Onlop_svChanged();
    partial void Onma_svChanging(string value);
    partial void Onma_svChanged();
    partial void Onngay_sinh_svChanging(string value);
    partial void Onngay_sinh_svChanged();
    partial void Ondia_chi_svChanging(string value);
    partial void Ondia_chi_svChanged();
    partial void Onsdt_svChanging(int value);
    partial void Onsdt_svChanged();
    partial void Onid_lop_thChanging(string value);
    partial void Onid_lop_thChanged();
    #endregion
		
		public tbl_SinhVien()
		{
			this._tbl_LichThis = new EntitySet<tbl_LichThi>(new Action<tbl_LichThi>(this.attach_tbl_LichThis), new Action<tbl_LichThi>(this.detach_tbl_LichThis));
			this._tbl_Lop = default(EntityRef<tbl_Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sv
		{
			get
			{
				return this._id_sv;
			}
			set
			{
				if ((this._id_sv != value))
				{
					this.Onid_svChanging(value);
					this.SendPropertyChanging();
					this._id_sv = value;
					this.SendPropertyChanged("id_sv");
					this.Onid_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_sv", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ten_sv
		{
			get
			{
				return this._ten_sv;
			}
			set
			{
				if ((this._ten_sv != value))
				{
					this.Onten_svChanging(value);
					this.SendPropertyChanging();
					this._ten_sv = value;
					this.SendPropertyChanged("ten_sv");
					this.Onten_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop_sv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string lop_sv
		{
			get
			{
				return this._lop_sv;
			}
			set
			{
				if ((this._lop_sv != value))
				{
					this.Onlop_svChanging(value);
					this.SendPropertyChanging();
					this._lop_sv = value;
					this.SendPropertyChanged("lop_sv");
					this.Onlop_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_sv", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string ma_sv
		{
			get
			{
				return this._ma_sv;
			}
			set
			{
				if ((this._ma_sv != value))
				{
					this.Onma_svChanging(value);
					this.SendPropertyChanging();
					this._ma_sv = value;
					this.SendPropertyChanged("ma_sv");
					this.Onma_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh_sv", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ngay_sinh_sv
		{
			get
			{
				return this._ngay_sinh_sv;
			}
			set
			{
				if ((this._ngay_sinh_sv != value))
				{
					this.Onngay_sinh_svChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh_sv = value;
					this.SendPropertyChanged("ngay_sinh_sv");
					this.Onngay_sinh_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi_sv", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string dia_chi_sv
		{
			get
			{
				return this._dia_chi_sv;
			}
			set
			{
				if ((this._dia_chi_sv != value))
				{
					this.Ondia_chi_svChanging(value);
					this.SendPropertyChanging();
					this._dia_chi_sv = value;
					this.SendPropertyChanged("dia_chi_sv");
					this.Ondia_chi_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt_sv", DbType="Int NOT NULL")]
		public int sdt_sv
		{
			get
			{
				return this._sdt_sv;
			}
			set
			{
				if ((this._sdt_sv != value))
				{
					this.Onsdt_svChanging(value);
					this.SendPropertyChanging();
					this._sdt_sv = value;
					this.SendPropertyChanged("sdt_sv");
					this.Onsdt_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lop_th", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string id_lop_th
		{
			get
			{
				return this._id_lop_th;
			}
			set
			{
				if ((this._id_lop_th != value))
				{
					if (this._tbl_Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_lop_thChanging(value);
					this.SendPropertyChanging();
					this._id_lop_th = value;
					this.SendPropertyChanged("id_lop_th");
					this.Onid_lop_thChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SinhVien_tbl_LichThi", Storage="_tbl_LichThis", ThisKey="id_sv", OtherKey="id_sv")]
		public EntitySet<tbl_LichThi> tbl_LichThis
		{
			get
			{
				return this._tbl_LichThis;
			}
			set
			{
				this._tbl_LichThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Lop_tbl_SinhVien", Storage="_tbl_Lop", ThisKey="id_lop_th", OtherKey="id_lop_th", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Lop tbl_Lop
		{
			get
			{
				return this._tbl_Lop.Entity;
			}
			set
			{
				tbl_Lop previousValue = this._tbl_Lop.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Lop.Entity = null;
						previousValue.tbl_SinhViens.Remove(this);
					}
					this._tbl_Lop.Entity = value;
					if ((value != null))
					{
						value.tbl_SinhViens.Add(this);
						this._id_lop_th = value.id_lop_th;
					}
					else
					{
						this._id_lop_th = default(string);
					}
					this.SendPropertyChanged("tbl_Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_LichThis(tbl_LichThi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_SinhVien = this;
		}
		
		private void detach_tbl_LichThis(tbl_LichThi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_SinhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LichThi")]
	public partial class tbl_LichThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_lt;
		
		private string _gio_lt;
		
		private string _phong_lt;
		
		private string _ngay_lt;
		
		private string _sbd_lt;
		
		private int _id_sv;
		
		private EntityRef<tbl_SinhVien> _tbl_SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ltChanging(int value);
    partial void Onid_ltChanged();
    partial void Ongio_ltChanging(string value);
    partial void Ongio_ltChanged();
    partial void Onphong_ltChanging(string value);
    partial void Onphong_ltChanged();
    partial void Onngay_ltChanging(string value);
    partial void Onngay_ltChanged();
    partial void Onsbd_ltChanging(string value);
    partial void Onsbd_ltChanged();
    partial void Onid_svChanging(int value);
    partial void Onid_svChanged();
    #endregion
		
		public tbl_LichThi()
		{
			this._tbl_SinhVien = default(EntityRef<tbl_SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_lt
		{
			get
			{
				return this._id_lt;
			}
			set
			{
				if ((this._id_lt != value))
				{
					this.Onid_ltChanging(value);
					this.SendPropertyChanging();
					this._id_lt = value;
					this.SendPropertyChanged("id_lt");
					this.Onid_ltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio_lt", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string gio_lt
		{
			get
			{
				return this._gio_lt;
			}
			set
			{
				if ((this._gio_lt != value))
				{
					this.Ongio_ltChanging(value);
					this.SendPropertyChanging();
					this._gio_lt = value;
					this.SendPropertyChanged("gio_lt");
					this.Ongio_ltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phong_lt", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string phong_lt
		{
			get
			{
				return this._phong_lt;
			}
			set
			{
				if ((this._phong_lt != value))
				{
					this.Onphong_ltChanging(value);
					this.SendPropertyChanging();
					this._phong_lt = value;
					this.SendPropertyChanged("phong_lt");
					this.Onphong_ltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_lt", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ngay_lt
		{
			get
			{
				return this._ngay_lt;
			}
			set
			{
				if ((this._ngay_lt != value))
				{
					this.Onngay_ltChanging(value);
					this.SendPropertyChanging();
					this._ngay_lt = value;
					this.SendPropertyChanged("ngay_lt");
					this.Onngay_ltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbd_lt", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sbd_lt
		{
			get
			{
				return this._sbd_lt;
			}
			set
			{
				if ((this._sbd_lt != value))
				{
					this.Onsbd_ltChanging(value);
					this.SendPropertyChanging();
					this._sbd_lt = value;
					this.SendPropertyChanged("sbd_lt");
					this.Onsbd_ltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sv", DbType="Int NOT NULL")]
		public int id_sv
		{
			get
			{
				return this._id_sv;
			}
			set
			{
				if ((this._id_sv != value))
				{
					if (this._tbl_SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_svChanging(value);
					this.SendPropertyChanging();
					this._id_sv = value;
					this.SendPropertyChanged("id_sv");
					this.Onid_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SinhVien_tbl_LichThi", Storage="_tbl_SinhVien", ThisKey="id_sv", OtherKey="id_sv", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_SinhVien tbl_SinhVien
		{
			get
			{
				return this._tbl_SinhVien.Entity;
			}
			set
			{
				tbl_SinhVien previousValue = this._tbl_SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_SinhVien.Entity = null;
						previousValue.tbl_LichThis.Remove(this);
					}
					this._tbl_SinhVien.Entity = value;
					if ((value != null))
					{
						value.tbl_LichThis.Add(this);
						this._id_sv = value.id_sv;
					}
					else
					{
						this._id_sv = default(int);
					}
					this.SendPropertyChanged("tbl_SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
